<?php return [
'nav'=>['dashboard'=>'主页','explore'=>'探索','transportation'=>'交通指南','about'=>'关于马来西亚','logout'=>'退出'],
'footer'=>['tagline'=>'陪你探索马来西亚的地方、文化与难忘旅程。','explore'=>'探索','saved'=>'收藏地点','transportation'=>'交通指南','discover'=>'发现马来西亚','about'=>'关于马来西亚','preferences'=>'地点偏好','profile'=>'我的资料','confidence'=>'安心规划','confidence_text'=>'探索精心挑选的目的地和实用的本地旅游信息。','rights'=>'版权所有。','made'=>'为探索马来西亚而打造。'],
'dashboard'=>['title'=>'主页','eyebrow'=>'你的马来西亚旅程从这里开始','welcome'=>'欢迎回来，:name。','intro'=>'发现精彩地点、规划理想旅程，并集中保存每一个旅游想法。','plan'=>'选择地点兴趣','view_saved'=>'查看收藏地点','next'=>'下一段旅程','explore_my'=>'探索马来西亚','glance'=>'概览','travel_dashboard'=>'你的旅游主页','saved'=>'收藏地点','collection'=>'你的目的地收藏','preferences'=>'地点偏好','personalise'=>'个性化你的主页','profile'=>'我的资料','identity'=>'管理你的账户','quick'=>'快捷入口','question'=>'你想做什么？','made_for'=>'为你推荐','build'=>'选择你喜欢的地点','build_text'=>'选择你想探索的马来西亚目的地类型。','update'=>'更新偏好','revisit'=>'重新查看收藏地点','revisit_text'=>'保存令你心动的目的地，为下一次出发做好准备。','open'=>'打开收藏地点','tip'=>'旅行提示','quote'=>'最好的旅程，往往从一个令你好奇的地方开始。','inspiration'=>'ExploreMY 灵感','your_interests'=>'你的地点兴趣','interest_intro'=>'主页正根据你选择的地点类别进行个性化。','no_interests'=>'你还没有选择地点偏好。','disabled'=>'个性化功能已关闭。请在个人资料中启用，才能使用地点偏好。','travel_notes'=>'你的旅行笔记','no_notes'=>'在个人资料中添加旅行笔记，让旅游计划显示在这里。'],
'profile'=>['title'=>'我的账户','centre'=>'账户中心','my_profile'=>'我的资料','intro'=>'管理个人信息、地点偏好及账户隐私。','back'=>'返回主页','check'=>'请检查你填写的资料。','connected'=>'Google 账户已连接','completion'=>'资料完成度','complete'=>'你的资料已经完整。','complete_hint'=>'完善资料以获得更完整的使用体验。','personal'=>'个人资料','place_preferences'=>'地点偏好','security'=>'安全与登录活动','privacy'=>'隐私设置','basic'=>'保持基本个人资料准确并及时更新。','name'=>'姓名','email'=>'电子邮箱','managed'=>'由你的 Google 账户管理','phone'=>'电话号码','dob'=>'出生日期','nationality'=>'国籍','travel_notes'=>'旅行笔记','notes_placeholder'=>'记录你想去的地方，或希望在马来西亚发现什么……','characters'=>'字符','destination_interests'=>'你的目的地兴趣','interest_desc'=>'文化、美食、自然、历史遗产及其他地点类别。','manage'=>'管理偏好','language_privacy'=>'语言与个性化','privacy_desc'=>'选择界面语言，并决定地点偏好是否用于个性化主页。','language'=>'界面语言','personalisation'=>'地点偏好个性化','personalisation_desc'=>'在主页显示你选择的地点兴趣和相关内容。','review'=>'保存前请检查你的更改。','save'=>'保存账户更改','auth_google'=>'你的账户认证由 Google 安全管理。','google_signin'=>'Google 登录','connected_as'=>'已连接：:email','recent'=>'最近登录记录','no_activity'=>'下次登录后，登录活动将显示在这里。','delete'=>'删除账户','delete_desc'=>'永久删除个人资料、地点偏好、收藏数据及登录记录。','delete_button'=>'删除我的账户','delete_question'=>'确定删除账户？','delete_warning'=>'此操作无法撤销。请输入 DELETE 进行确认。','type_delete'=>'输入 DELETE','cancel'=>'取消','delete_forever'=>'永久删除','change'=>'更换'],
'preferences'=>['page'=>'地点偏好','title'=>'你喜欢探索哪些地方？','intro'=>'选择目的地类别。只有启用个性化后，这些选择才会显示在主页。','selected'=>'已选择 :count 项','save'=>'保存地点偏好','back'=>'返回个人资料','none'=>'目前没有可选择的地点类别。'],
'messages'=>['welcome'=>'欢迎回来。','profile_updated'=>'账户资料已成功保存。','account_deleted'=>'你的账户及相关资料已永久删除。','preferences_saved'=>'地点偏好已更新。','clear'=>'清除'],
'categories'=>['adventure'=>'探险','beach'=>'海滩','culture'=>'文化','food'=>'美食','history'=>'历史','nature'=>'自然','shopping'=>'购物'],
];
