<!DOCTYPE html><html lang="{{ app()->getLocale() }}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ __('pages.about.title') }} - ExploreMY</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/malaysia-pages.css') }}"></head><body class="about-malaysia-page">
@include('components.navbar')
<x-page-back
    :href="auth()->check() ? route('dashboard') : route('explore')"
    :label="auth()->check() ? __('ui.profile.back') : __('attraction.back')"
/>
<main class="info-page">
    <section class="about-hero"><div class="container"><span class="page-eyebrow">{{ __('pages.about.eyebrow') }}</span><h1>{{ __('pages.about.heading') }}</h1><p>{{ __('pages.about.intro') }}</p><div class="hero-facts"><span><strong>13</strong> {{ __('pages.about.states') }}</span><span><strong>3</strong> {{ __('pages.about.territories') }}</span><span><strong>{{ __('misc.about.malay') }}</strong> {{ __('pages.about.language') }}</span></div></div></section>
    <section class="container story-section"><div class="story-intro"><span class="page-eyebrow dark">{{ __('pages.about.contrast') }}</span><h2>{{ __('pages.about.experiences') }}</h2></div><div class="story-copy"><p>{{ __('pages.about.story1') }}</p><p>{{ __('pages.about.story2') }}</p></div></section>
    <section class="container culture-section">
        <div class="culture-heading"><span class="page-eyebrow dark">{{ __('pages.about.living') }}</span><h2>{{ __('pages.about.traditions') }}</h2><p>{{ __('pages.about.culture_intro') }}</p></div>
        <div class="culture-gallery">
            <article class="culture-card culture-card-wide"><div class="culture-image"><img src="{{ asset('images/malaysia/culture-festival.png') }}" alt="" loading="lazy"><span>{{ __('pages.about.people') }}</span></div><div class="culture-content"><small>01 / {{ __('pages.about.community') }}</small><h3>{{ __('pages.about.calendar') }}</h3><p>{{ __('pages.about.calendar_text') }}</p></div></article>
            <article class="culture-card"><div class="culture-image"><img src="{{ asset('images/malaysia/malaysian-food.png') }}" alt="" loading="lazy"><span>{{ __('pages.about.flavours') }}</span></div><div class="culture-content"><small>02 / {{ __('pages.about.food') }}</small><h3>{{ __('pages.about.meeting') }}</h3><p>{{ __('pages.about.meeting_text') }}</p></div></article>
            <article class="culture-card"><div class="culture-image"><img src="{{ asset('images/malaysia/heritage-architecture.png') }}" alt="" loading="lazy"><span>{{ __('pages.about.craft') }}</span></div><div class="culture-content"><small>03 / {{ __('pages.about.architecture') }}</small><h3>{{ __('pages.about.stories') }}</h3><p>{{ __('pages.about.stories_text') }}</p></div></article>
        </div>
    </section>
    <section class="culture-band"><div class="container"><div><strong>140+</strong><span>{{ __('pages.about.languages') }}</span></div><div><strong>4</strong><span>{{ __('pages.about.unesco') }}</span></div><div><strong>30M+</strong><span>{{ __('pages.about.population') }}</span></div><p>{{ __('pages.about.strength') }}</p></div></section>
    <section class="container highlights"><article><span>01</span><h3>{{ __('pages.about.performing') }}</h3><p>{{ __('pages.about.performing_text') }}</p></article><article><span>02</span><h3>{{ __('pages.about.crafts') }}</h3><p>{{ __('pages.about.crafts_text') }}</p></article><article><span>03</span><h3>{{ __('pages.about.nature') }}</h3><p>{{ __('pages.about.nature_text') }}</p></article></section>
    <section class="container travel-essentials"><div><span class="page-eyebrow dark">{{ __('pages.about.know') }}</span><h2>{{ __('pages.about.glance') }}</h2><p>{{ __('pages.about.welcome') }}</p></div><dl><div><dt>{{ __('pages.about.capital') }}</dt><dd>Kuala Lumpur</dd></div><div><dt>{{ __('pages.about.admin') }}</dt><dd>Putrajaya</dd></div><div><dt>{{ __('pages.about.currency') }}</dt><dd>{{ __('misc.about.ringgit') }}</dd></div><div><dt>{{ __('pages.about.climate') }}</dt><dd>{{ __('pages.about.tropical') }}</dd></div></dl></section>
    <section class="container about-cta"><div><span class="page-eyebrow">{{ __('pages.about.ready') }}</span><h2>{{ __('pages.about.speak') }}</h2></div><a href="{{ route('profile') }}#preferences">{{ __('pages.about.personalise') }} &rarr;</a></section>
</main>@include('components.footer')</body></html>
