<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>About Malaysia - ExploreMY</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/malaysia-pages.css') }}"></head><body>
@include('components.navbar')
<main class="info-page">
    <section class="about-hero"><div class="container"><span class="page-eyebrow">Truly Asia</span><h1>Meet Malaysia</h1><p>A country where ancient rainforests, vibrant cities, tropical islands and many cultures come together in one remarkable destination.</p><div class="hero-facts"><span><strong>13</strong> states</span><span><strong>3</strong> federal territories</span><span><strong>Malay</strong> national language</span></div></div></section>
    <section class="container story-section"><div class="story-intro"><span class="page-eyebrow dark">A country of contrasts</span><h2>One nation, countless experiences</h2></div><div class="story-copy"><p>Malaysia is located in Southeast Asia and is made up of two distinct regions: Peninsular Malaysia and East Malaysia on the island of Borneo. Between them, travellers encounter modern skylines, historic trading towns, cool highlands, pristine beaches and some of the world's oldest tropical rainforests.</p><p>Its identity is shaped by Malay, Chinese, Indian, Indigenous and many other communities. This diversity is reflected in everyday life—from languages and celebrations to architecture and an extraordinary food culture.</p></div></section>
    <section class="container culture-section">
        <div class="culture-heading"><span class="page-eyebrow dark">Living culture</span><h2>Many traditions, shared proudly</h2><p>Malaysia's multicultural character is experienced through its people, celebrations, food, art and everyday rituals.</p></div>
        <div class="culture-gallery">
            <article class="culture-card culture-card-wide"><div class="culture-image"><img src="{{ asset('images/malaysia/culture-festival.png') }}" alt="Malaysian cultural performers in traditional attire" loading="lazy"><span>People & celebrations</span></div><div class="culture-content"><small>01 / Community</small><h3>A calendar filled with celebration</h3><p>Hari Raya Aidilfitri, Chinese New Year, Deepavali, Gawai and Kaamatan bring communities together through open houses, music, dance and shared meals.</p></div></article>
            <article class="culture-card"><div class="culture-image"><img src="{{ asset('images/malaysia/malaysian-food.png') }}" alt="A table of Malaysian dishes including nasi lemak and satay" loading="lazy"><span>Flavours</span></div><div class="culture-content"><small>02 / Food</small><h3>A meeting place of flavours</h3><p>Malay, Chinese, Indian, Peranakan and Indigenous cooking traditions make every region—and often every street—taste distinct.</p></div></article>
            <article class="culture-card"><div class="culture-image"><img src="{{ asset('images/malaysia/heritage-architecture.png') }}" alt="Traditional Malaysian wooden architecture at dusk" loading="lazy"><span>Craft & heritage</span></div><div class="culture-content"><small>03 / Architecture</small><h3>Stories built into every detail</h3><p>Carved timber homes, mosques, temples, clan houses and colonial shophouses reveal centuries of skill, belief and exchange.</p></div></article>
        </div>
    </section>

    <section class="culture-band"><div class="container"><div><strong>140+</strong><span>languages spoken</span></div><div><strong>4</strong><span>UNESCO World Heritage Sites</span></div><div><strong>30M+</strong><span>people and countless stories</span></div><p>Malaysia's strength lies in the way difference becomes part of a shared national identity.</p></div></section>

    <section class="container highlights"><article><span>01</span><h3>Performing arts</h3><p>Discover mak yong theatre, wayang kulit shadow puppetry, kompang ensembles and the rhythms of sape music from Borneo.</p></article><article><span>02</span><h3>Traditional crafts</h3><p>Batik, songket weaving, beadwork, wood carving and silverwork preserve knowledge passed through generations.</p></article><article><span>03</span><h3>Nature & identity</h3><p>Rainforests, rivers and the sea shape Indigenous traditions, local livelihoods and a deep respect for the land.</p></article></section>
    <section class="container travel-essentials"><div><span class="page-eyebrow dark">Good to know</span><h2>Malaysia at a glance</h2><p>Warm hospitality and excellent connections make Malaysia an approachable destination for every kind of traveller.</p></div><dl><div><dt>Capital</dt><dd>Kuala Lumpur</dd></div><div><dt>Administrative capital</dt><dd>Putrajaya</dd></div><div><dt>Currency</dt><dd>Malaysian Ringgit (MYR)</dd></div><div><dt>Climate</dt><dd>Tropical year-round</dd></div></dl></section>
    <section class="container about-cta"><div><span class="page-eyebrow">Ready to explore?</span><h2>Find the Malaysia that speaks to you.</h2></div><a href="{{ route('travel-preferences.edit') }}">Personalise your journey &rarr;</a></section>
</main>@include('components.footer')</body></html>
