<!DOCTYPE html><html lang="{{ app()->getLocale() }}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ __('ui.profile.title') }} - ExploreMY</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/profile.css') }}"></head><body>
@include('components.navbar')
<main class="container profile-page">
<header class="account-heading"><div><span>{{ __('ui.profile.centre') }}</span><h1>{{ __('ui.profile.my_profile') }}</h1><p>{{ __('ui.profile.intro') }}</p></div><a href="{{ route('dashboard') }}">{{ __('ui.profile.back') }}</a></header>
@if(session('success'))<div class="profile-alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="profile-alert error"><strong>{{ __('ui.profile.check') }}</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="account-layout"><aside class="account-sidebar"><div class="identity-card"><button type="button" class="avatar-button" onclick="document.getElementById('profile_picture').click()"><img src="{{ $user->profile_picture }}" id="avatarPreview" alt="{{ $user->name }}"><span>{{ __('ui.profile.change') }}</span></button><h2>{{ $user->name }}</h2><p>{{ $user->email }}</p><span class="google-status"><i></i>{{ __('ui.profile.connected') }}</span></div><div class="completion-card"><div><strong>{{ __('ui.profile.completion') }}</strong><span>{{ $completion }}%</span></div><div class="completion-track"><i style="width:{{ $completion }}%"></i></div><p>{{ $completion===100 ? __('ui.profile.complete') : __('ui.profile.complete_hint') }}</p></div><nav class="account-nav"><a href="#personal">{{ __('ui.profile.personal') }}</a><a href="#preferences">{{ __('ui.profile.place_preferences') }}</a><a href="#security">{{ __('ui.profile.security') }}</a><a href="#privacy">{{ __('ui.profile.privacy') }}</a></nav></aside>
<div class="account-content"><form method="POST" action="{{ route('profile.update') }}" enctype="multipart/form-data">@csrf<input type="file" name="profile_picture" id="profile_picture" accept="image/*" hidden onchange="previewImage(event)">
<section class="account-panel" id="personal"><div class="panel-heading"><span>01</span><div><h2>{{ __('ui.profile.personal') }}</h2><p>{{ __('ui.profile.basic') }}</p></div></div><div class="form-grid">
<label><span>{{ __('ui.profile.name') }} *</span><input type="text" name="name" value="{{ old('name',$user->name) }}" required></label><label><span>{{ __('ui.profile.email') }}</span><input type="email" value="{{ $user->email }}" disabled><small>{{ __('ui.profile.managed') }}</small></label><label><span>{{ __('ui.profile.phone') }}</span><input type="tel" name="phone" value="{{ old('phone',$user->phone) }}" placeholder="+60 12-345 6789"></label><label><span>{{ __('ui.profile.dob') }}</span><input type="date" name="date_of_birth" value="{{ old('date_of_birth',optional($user->date_of_birth)->format('Y-m-d')) }}" max="{{ now()->subDay()->format('Y-m-d') }}"></label><label class="full-field"><span>{{ __('ui.profile.nationality') }}</span><input type="text" name="nationality" value="{{ old('nationality',$user->nationality) }}"></label><label class="full-field"><span>{{ __('ui.profile.travel_notes') }}</span><textarea name="bio" maxlength="500" rows="4" placeholder="{{ __('ui.profile.notes_placeholder') }}">{{ old('bio',$user->bio) }}</textarea><small><b id="bioCount">{{ strlen(old('bio',$user->bio??'')) }}</b>/500 {{ __('ui.profile.characters') }}</small></label></div></section>
<section class="account-panel" id="preferences"><div class="panel-heading"><span>02</span><div><h2>{{ __('ui.profile.place_preferences') }}</h2><p>{{ __('ui.preferences.intro') }}</p></div></div><div class="linked-setting"><div><strong>{{ __('ui.profile.destination_interests') }}</strong><p>{{ __('ui.profile.interest_desc') }}</p></div><a href="{{ route('travel-preferences.edit') }}">{{ __('ui.profile.manage') }} &rarr;</a></div></section>
<section class="account-panel" id="privacy"><div class="panel-heading"><span>03</span><div><h2>{{ __('ui.profile.language_privacy') }}</h2><p>{{ __('ui.profile.privacy_desc') }}</p></div></div><label class="select-setting"><span>{{ __('ui.profile.language') }}</span><select name="preferred_language"><option value="en" @selected(old('preferred_language',$user->preferred_language)==='en')>English</option><option value="ms" @selected(old('preferred_language',$user->preferred_language)==='ms')>Bahasa Melayu</option><option value="zh" @selected(old('preferred_language',$user->preferred_language)==='zh')>中文</option></select></label><label class="switch-setting"><span><strong>{{ __('ui.profile.personalisation') }}</strong><small>{{ __('ui.profile.personalisation_desc') }}</small></span><input type="checkbox" name="personalisation_consent" value="1" @checked(old('personalisation_consent',$user->personalisation_consent))><i></i></label></section><div class="save-bar"><span>{{ __('ui.profile.review') }}</span><button type="submit">{{ __('ui.profile.save') }}</button></div></form>
<section class="account-panel" id="security"><div class="panel-heading"><span>04</span><div><h2>{{ __('ui.profile.security') }}</h2><p>{{ __('ui.profile.auth_google') }}</p></div></div><div class="security-provider"><div class="provider-icon">G</div><div><strong>{{ __('ui.profile.google_signin') }}</strong><small>{{ __('ui.profile.connected_as',['email'=>$user->email]) }}</small></div><span>{{ __('ui.profile.connected') }}</span></div><h3 class="activity-title">{{ __('ui.profile.recent') }}</h3><div class="activity-list">@forelse($activities as $activity)<div><i></i><span><strong>{{ $activity->logged_in_at->translatedFormat('d M Y, h:i A') }}</strong><small>{{ Str::limit($activity->user_agent?:__('misc.dashboard.unknown_device'),75) }}</small></span><b>{{ $activity->ip_address?:__('misc.dashboard.unknown_ip') }}</b></div>@empty<div class="empty-activity">{{ __('ui.profile.no_activity') }}</div>@endforelse</div></section>
<section class="account-panel danger-panel"><div><h2>{{ __('ui.profile.delete') }}</h2><p>{{ __('ui.profile.delete_desc') }}</p></div><button type="button" onclick="document.getElementById('deleteDialog').showModal()">{{ __('ui.profile.delete_button') }}</button></section></div></div></main>
<dialog id="deleteDialog" class="delete-dialog"><form method="POST" action="{{ route('profile.destroy') }}">@csrf @method('DELETE')<button type="button" class="dialog-close" onclick="this.closest('dialog').close()">&times;</button><span class="danger-icon">!</span><h2>{{ __('ui.profile.delete_question') }}</h2><p>{{ __('ui.profile.delete_warning') }}</p><input type="text" name="confirmation" placeholder="{{ __('ui.profile.type_delete') }}" required pattern="DELETE"><div><button type="button" onclick="this.closest('dialog').close()">{{ __('ui.profile.cancel') }}</button><button type="submit">{{ __('ui.profile.delete_forever') }}</button></div></form></dialog>
@include('components.footer')<script>function previewImage(e){if(e.target.files[0])document.getElementById('avatarPreview').src=URL.createObjectURL(e.target.files[0])}const bio=document.querySelector('[name="bio"]');bio?.addEventListener('input',()=>document.getElementById('bioCount').textContent=bio.value.length);</script></body></html>
