<!DOCTYPE html><html lang="{{ app()->getLocale() }}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ __('ui.profile.title') }} - ExploreMY</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/profile.css') }}?v={{ filemtime(public_path('css/profile.css')) }}"></head><body>
@include('components.navbar')
<x-page-back :href="route('dashboard')" :label="__('ui.profile.back')" />
<main class="container profile-page">
<div id="profile-save-errors" class="profile-alert error" role="alert" tabindex="-1" hidden data-failed="{{ __('profile_errors.failed') }}" data-network="{{ __('profile_errors.network') }}"></div>
<header class="account-heading"><div><span>{{ __('ui.profile.centre') }}</span><h1>{{ __('ui.profile.my_profile') }}</h1><p>{{ __('profile_simple.intro') }}</p></div></header>
@if(session('success'))<div class="profile-alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="profile-alert error"><strong>{{ __('ui.profile.check') }}</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="account-layout profile-single-layout"><div class="account-content"><form method="POST" action="{{ route('profile.update') }}" enctype="multipart/form-data" class="profile-settings-box" aria-labelledby="profile-settings-title" data-ajax-crud data-profile-update>@csrf<input type="file" name="profile_picture" id="profile_picture" accept="image/*" hidden onchange="previewImage(event)">

<header class="profile-settings-heading"><h2 id="profile-settings-title">{{ __('profile_simple.settings_title') }}</h2><p>{{ __('profile_simple.settings_help') }}</p></header><div class="identity-card profile-settings-identity"><button type="button" aria-label="{{ __('profile_simple.change_photo') }}" class="avatar-button" onclick="document.getElementById('profile_picture').click()"><img src="{{ $user->profile_picture ?: asset('images/default-avatar.svg') }}" id="avatarPreview" alt="{{ $user->name }}" referrerpolicy="no-referrer" data-fallback="{{ asset('images/default-avatar.svg') }}" onerror="this.onerror=null;this.src=this.dataset.fallback"><span>{{ __('profile_simple.change_photo') }}</span></button><p class="profile-photo-help">{{ __('profile_simple.photo_help') }}</p><h2 data-profile-name>{{ $user->name }}</h2><p>{{ $user->email }}</p><span class="google-status"><i></i>{{ __('ui.profile.connected') }}</span></div><section class="account-panel profile-language-panel" aria-labelledby="profile-language-title">
    <div class="panel-heading"><div><h2 id="profile-language-title">{{ __('ui.profile.language') }}</h2><p id="profile-language-help">{{ __('profile_simple.language_help') }}</p></div></div>
    <div class="profile-language-options" role="radiogroup" aria-labelledby="profile-language-title" aria-describedby="profile-language-help">
        @foreach(['zh' => ['中文', 'Chinese'], 'ms' => ['Melayu', 'Malay'], 'en' => ['English', 'English']] as $code => $language)
            <label class="profile-language-option">
                <input type="radio" name="preferred_language" value="{{ $code }}" @checked(old('preferred_language', $user->preferred_language) === $code) required>
                <span class="profile-language-copy"><strong lang="{{ $code }}">{{ $language[0] }}</strong><small>{{ $language[1] }}</small></span>
            </label>
        @endforeach
    </div>
</section><section class="account-panel" id="preferences"><div class="panel-heading"><div><h2>{{ __('ui.profile.place_preferences') }}</h2><p>{{ __('profile_simple.preferences_help') }}</p></div></div><div class="simple-preferences">@foreach($categories as $category)<label class="simple-preference"><input type="checkbox" name="preferences[]" value="{{ $category->preference_id }}" @checked(in_array($category->preference_id, old('preferences',$selectedPreferences)))><strong>{{ $category->localized_name }}</strong></label>@endforeach</div></section>
<div class="save-bar profile-save-bar"><p id="profile-save-status" role="status" aria-live="polite" data-unsaved="{{ __('profile_simple.unsaved') }}" data-saved="{{ __('profile_simple.saved') }}" data-failed="{{ __('profile_simple.save_failed') }}">{{ __('profile_simple.save_help') }}</p><button type="submit">{{ __('profile_simple.save_button') }}</button></div></form>
<details class="account-panel recent-logins" id="security"><summary>{{ __('ui.profile.recent') }}</summary><div class="activity-list">@forelse($activities as $activity)<div><i></i><span><strong>{{ $activity->logged_in_at->translatedFormat('d M Y, h:i A') }}</strong><small>{{ Str::limit($activity->user_agent?:__('misc.dashboard.unknown_device'),75) }}</small></span><b>{{ $activity->ip_address?:__('misc.dashboard.unknown_ip') }}</b></div>@empty<div class="empty-activity">{{ __('ui.profile.no_activity') }}</div>@endforelse</div></details>
<section class="account-panel danger-panel"><div><h2>{{ __('ui.profile.delete') }}</h2><p>{{ __('ui.profile.delete_desc') }}</p></div><button type="button" onclick="document.getElementById('deleteDialog').showModal()">{{ __('ui.profile.delete_button') }}</button></section></div></div></main>
<dialog id="deleteDialog" class="delete-dialog"><form method="POST" action="{{ route('profile.destroy') }}">@csrf @method('DELETE')<button type="button" class="dialog-close" onclick="this.closest('dialog').close()">&times;</button><span class="danger-icon">!</span><h2>{{ __('ui.profile.delete_question') }}</h2><p>{{ __('ui.profile.delete_warning') }}</p><input type="text" name="confirmation" placeholder="{{ __('ui.profile.type_delete') }}" required pattern="DELETE"><div><button type="button" onclick="this.closest('dialog').close()">{{ __('ui.profile.cancel') }}</button><button type="submit">{{ __('ui.profile.delete_forever') }}</button></div></form></dialog>
@include('components.footer')<script>function previewImage(e){if(e.target.files[0])document.getElementById('avatarPreview').src=URL.createObjectURL(e.target.files[0])}</script><script src="{{ asset('js/profile-save.js') }}?v={{ filemtime(public_path('js/profile-save.js')) }}" defer></script></body></html>
