<!DOCTYPE html><html lang="{{ app()->getLocale() }}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ __('ui.preferences.page') }} - ExploreMY</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/profile.css') }}"></head><body>
@include('components.navbar')
<main class="container profile-page preference-page">
<header class="account-heading"><div><span>{{ __('ui.profile.place_preferences') }}</span><h1>{{ __('ui.preferences.title') }}</h1><p>{{ __('ui.preferences.intro') }}</p></div><a href="{{ route('profile') }}">{{ __('ui.preferences.back') }}</a></header>
@if(session('success'))<div class="profile-alert success">{{ session('success') }}</div>@endif @if($errors->any())<div class="profile-alert error">{{ $errors->first() }}</div>@endif
<form action="{{ route('travel-preferences.update') }}" method="POST" class="preference-form">@csrf
<div class="preference-toolbar"><strong>{{ __('ui.preferences.selected',['count'=>count($selectedPreferences)]) }}</strong><button type="button" id="clearPreferences">{{ __('ui.messages.clear') }}</button></div>
<div class="preference-card-grid">@forelse($categories as $category)<label class="preference-choice"><input type="checkbox" name="preferences[]" value="{{ $category->preference_id }}" @checked(in_array($category->preference_id,$selectedPreferences))><span class="choice-check">&#10003;</span><span class="choice-icon">{{ Str::upper(Str::substr($category->localized_name,0,1)) }}</span><strong>{{ $category->localized_name }}</strong><small>{{ __('ui.profile.destination_interests') }}</small></label>@empty<div class="empty-activity">{{ __('ui.preferences.none') }}</div>@endforelse</div>
<div class="preference-actions"><a href="{{ route('profile') }}" class="btn btn-profile-secondary">{{ __('ui.preferences.back') }}</a><button type="submit" class="btn btn-profile-primary">{{ __('ui.preferences.save') }}</button></div></form></main>
@include('components.footer')
<script>const boxes=[...document.querySelectorAll('.preference-choice input')],count=document.querySelector('.preference-toolbar strong'),template=@json(__('ui.preferences.selected',['count'=>'__COUNT__']));function updatePreferenceCount(){count.textContent=template.replace('__COUNT__',boxes.filter(box=>box.checked).length)}boxes.forEach(box=>box.addEventListener('change',updatePreferenceCount));document.getElementById('clearPreferences')?.addEventListener('click',()=>{boxes.forEach(box=>box.checked=false);updatePreferenceCount()});</script>
</body></html>
