<!DOCTYPE html><html lang="{{ app()->getLocale() }}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $attraction->exists ? __('admin.edit_word') : __('admin.add_word') }} {{ __('admin.attraction') }} - ExploreMY Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/admin.css') }}"></head><body>
@include('components.admin-navbar')
<main class="container admin-page"><header class="admin-heading"><div><span>{{ __('admin.catalogue') }}</span><h1>{{ $attraction->exists ? __('admin.edit_heading') : __('admin.add_heading') }}</h1><p>{{ __('admin.required') }}</p></div><a class="admin-back" href="{{ route('admin.attractions.index') }}">&larr; {{ __('admin.back') }}</a></header>
@if($errors->any())<div class="admin-errors"><strong>{{ __('admin.correct') }}</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="admin-form" method="POST" enctype="multipart/form-data" action="{{ $attraction->exists ? route('admin.attractions.update',$attraction) : route('admin.attractions.store') }}">@csrf @if($attraction->exists)@method('PUT')@endif
<section><div class="form-section-title"><span>01</span><div><h2>{{ __('admin.basic') }}</h2><p>{{ __('admin.basic_intro') }}</p></div></div><div class="admin-form-grid"><label><span>{{ __('admin.place_id') }} *</span><input name="place_id" value="{{ old('place_id',$attraction->place_id) }}" required maxlength="255"><small>{{ __('admin.place_id_help') }}</small></label><label><span>{{ __('admin.name') }} *</span><input name="attraction_name" value="{{ old('attraction_name',$attraction->attraction_name) }}" required maxlength="100"></label><label><span>{{ __('admin.state') }} *</span><select name="state_id" required><option value="">{{ __('admin.select_state') }}</option>@foreach($states as $state)<option value="{{ $state->state_id }}" @selected(old('state_id',$attraction->state_id)==$state->state_id)>{{ $state->state_name }}</option>@endforeach</select></label><label><span>{{ __('admin.categories') }}</span><input name="category" value="{{ old('category',$attraction->category) }}" maxlength="255" placeholder="{{ __('admin.category_placeholder') }}"><small>{{ __('admin.category_help') }}</small></label><label class="wide"><span>{{ __('admin.location') }} *</span><input name="location" value="{{ old('location',$attraction->location) }}" required maxlength="255"></label><label class="wide"><span>{{ __('admin.description') }}</span><textarea name="description" rows="4">{{ old('description',$attraction->description) }}</textarea></label></div></section>
<section><div class="form-section-title"><span>02</span><div><h2>{{ __('admin.visitor') }}</h2><p>{{ __('admin.visitor_intro') }}</p></div></div><div class="admin-form-grid"><label class="wide"><span>{{ __('admin.hours') }}</span><textarea name="operating_hours" rows="7" placeholder="{{ __('admin.hours_placeholder') }}">{{ old('operating_hours',$attraction->operating_hours) }}</textarea></label><label><span>{{ __('admin.fee') }} *</span><input name="entrance_fee" value="{{ old('entrance_fee',$attraction->entrance_fee ?: __('admin.price_unavailable')) }}" required maxlength="100"></label><label><span>{{ __('admin.budget') }} *</span><select name="budget_level" required>@foreach(['Price unavailable','Free','Low','Moderate','High'] as $level)<option value="{{ $level }}" @selected(old('budget_level',$attraction->budget_level)===$level)>{{ __('admin.' . ['Price unavailable'=>'price_unavailable','Free'=>'free','Low'=>'low','Moderate'=>'moderate','High'=>'high'][$level]) }}</option>@endforeach</select></label><label><span>{{ __('admin.transport') }}</span><input name="nearby_transport" value="{{ old('nearby_transport',$attraction->nearby_transport) }}" maxlength="100"></label><label><span>{{ __('admin.rating') }}</span><input type="number" name="rating" value="{{ old('rating',$attraction->rating) }}" min="0" max="5" step="0.1" placeholder="0.0 – 5.0"></label></div></section>
<section><div class="form-section-title"><span>03</span><div><h2>{{ __('admin.image') }}</h2><p>{{ __('admin.image_intro') }}</p></div></div><label class="image-upload"><input type="file" name="image" accept="image/*" id="imageInput"><span id="imagePreview">@if($attraction->image_path)<img src="{{ $attraction->image_path }}" alt="{{ __('admin.current_image') }}">@else<b>+</b><strong>{{ __('admin.choose_image') }}</strong><small>{{ __('admin.optional') }}</small>@endif</span></label></section>
<div class="admin-save-bar"><a href="{{ route('admin.attractions.index') }}">{{ __('admin.cancel') }}</a><button type="submit">{{ $attraction->exists ? __('admin.save') : __('admin.create') }}</button></div></form></main>
<script>const imagePreviewAlt={{ Illuminate\Support\Js::from(__('admin.preview')) }};document.getElementById('imageInput').addEventListener('change',e=>{if(!e.target.files[0])return;document.getElementById('imagePreview').innerHTML=`<img src="${URL.createObjectURL(e.target.files[0])}" alt="${imagePreviewAlt}">`});</script></body></html>
