<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $attraction->exists ? 'Edit' : 'Add' }} Attraction - ExploreMY Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/admin.css') }}"></head><body>
@include('components.admin-navbar')
<main class="container admin-page"><header class="admin-heading"><div><span>Place catalogue</span><h1>{{ $attraction->exists ? 'Edit attraction' : 'Add a new attraction' }}</h1><p>Fields marked with an asterisk are required.</p></div><a class="admin-back" href="{{ route('admin.attractions.index') }}">&larr; Back to list</a></header>
@if($errors->any())<div class="admin-errors"><strong>Please correct the following:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="admin-form" method="POST" enctype="multipart/form-data" action="{{ $attraction->exists ? route('admin.attractions.update',$attraction) : route('admin.attractions.store') }}">@csrf @if($attraction->exists)@method('PUT')@endif
<section><div class="form-section-title"><span>01</span><div><h2>Basic information</h2><p>Identity, location and classification.</p></div></div><div class="admin-form-grid"><label><span>Place ID *</span><input name="place_id" value="{{ old('place_id',$attraction->place_id) }}" required maxlength="255"><small>Unique external or internal place identifier.</small></label><label><span>Attraction name *</span><input name="attraction_name" value="{{ old('attraction_name',$attraction->attraction_name) }}" required maxlength="100"></label><label><span>State *</span><select name="state_id" required><option value="">Select a state</option>@foreach($states as $state)<option value="{{ $state->state_id }}" @selected(old('state_id',$attraction->state_id)==$state->state_id)>{{ $state->state_name }}</option>@endforeach</select></label><label><span>Categories</span><input name="category" value="{{ old('category',$attraction->category) }}" maxlength="255" placeholder="Nature, Family, Adventure"><small>Separate multiple categories with commas.</small></label><label class="wide"><span>Full location *</span><input name="location" value="{{ old('location',$attraction->location) }}" required maxlength="255"></label><label class="wide"><span>Description</span><textarea name="description" rows="4">{{ old('description',$attraction->description) }}</textarea></label></div></section>
<section><div class="form-section-title"><span>02</span><div><h2>Visitor information</h2><p>Opening times, price, access and public rating.</p></div></div><div class="admin-form-grid"><label class="wide"><span>Operating hours</span><textarea name="operating_hours" rows="7" placeholder="Monday: 10:00 AM – 6:00 PM">{{ old('operating_hours',$attraction->operating_hours) }}</textarea></label><label><span>Entrance fee *</span><input name="entrance_fee" value="{{ old('entrance_fee',$attraction->entrance_fee ?: 'Price unavailable') }}" required maxlength="100"></label><label><span>Budget level *</span><select name="budget_level" required>@foreach(['Price unavailable','Free','Low','Moderate','High'] as $level)<option @selected(old('budget_level',$attraction->budget_level)===$level)>{{ $level }}</option>@endforeach</select></label><label><span>Nearby transport</span><input name="nearby_transport" value="{{ old('nearby_transport',$attraction->nearby_transport) }}" maxlength="100"></label><label><span>Rating</span><input type="number" name="rating" value="{{ old('rating',$attraction->rating) }}" min="0" max="5" step="0.1" placeholder="0.0 – 5.0"></label></div></section>
<section><div class="form-section-title"><span>03</span><div><h2>Attraction image</h2><p>Upload a JPG, PNG or WebP image up to 3 MB.</p></div></div><label class="image-upload"><input type="file" name="image" accept="image/*" id="imageInput"><span id="imagePreview">@if($attraction->image_path)<img src="{{ $attraction->image_path }}" alt="Current image">@else<b>+</b><strong>Choose an image</strong><small>Optional</small>@endif</span></label></section>
<div class="admin-save-bar"><a href="{{ route('admin.attractions.index') }}">Cancel</a><button type="submit">{{ $attraction->exists ? 'Save changes' : 'Create attraction' }}</button></div></form></main>
<script>document.getElementById('imageInput').addEventListener('change',e=>{if(!e.target.files[0])return;document.getElementById('imagePreview').innerHTML=`<img src="${URL.createObjectURL(e.target.files[0])}" alt="Image preview">`});</script></body></html>
