<!DOCTYPE html><html lang="{{ app()->getLocale() }}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ __('admin.manage_title') }}</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/admin.css') }}"></head><body>
@include('components.admin-navbar')
<main class="container admin-page"><header class="admin-heading"><div><span>{{ __('admin.administration') }}</span><h1>{{ __('admin.management') }}</h1><p>{{ __('admin.management_intro') }}</p></div><a href="{{ route('admin.attractions.create') }}">+ {{ __('admin.add') }}</a></header>
@if(session('success'))<div class="admin-alert">{{ session('success') }}</div>@endif
<section class="admin-summary"><div><small>{{ __('admin.total') }}</small><strong>{{ $attractions->total() }}</strong></div><form method="GET"><input type="search" name="search" value="{{ request('search') }}" placeholder="{{ __('admin.search_placeholder') }}"><button>{{ __('admin.search') }}</button>@if(request('search'))<a href="{{ route('admin.attractions.index') }}">{{ __('admin.clear') }}</a>@endif</form></section>
<section class="admin-table-card"><div class="admin-table-wrap"><table><thead><tr><th>{{ __('admin.attraction') }}</th><th>{{ __('admin.state') }}</th><th>{{ __('admin.category') }}</th><th>{{ __('admin.rating') }}</th><th>{{ __('admin.saved') }}</th><th>{{ __('admin.actions') }}</th></tr></thead><tbody>
@forelse($attractions as $attraction)<tr><td><div class="admin-place"><span>@if($attraction->image_path)<img src="{{ $attraction->image_path }}" alt="">@else{{ Str::upper(Str::substr($attraction->attraction_name,0,2)) }}@endif</span><div><strong>{{ $attraction->attraction_name }}</strong><small>{{ Str::limit($attraction->location,55) }}</small></div></div></td><td>{{ $attraction->state->state_name }}</td><td>{{ $attraction->category ?: '—' }}</td><td>{{ $attraction->rating ? number_format($attraction->rating,1) : '—' }}</td><td>{{ $attraction->saved_by_users_count }}</td><td><div class="table-actions"><a href="{{ route('admin.attractions.edit',$attraction) }}">{{ __('admin.edit') }}</a><button type="button" data-delete-url="{{ route('admin.attractions.destroy',$attraction) }}" data-name="{{ $attraction->attraction_name }}">{{ __('admin.delete') }}</button></div></td></tr>
@empty<tr><td colspan="6" class="admin-empty">{{ __('admin.empty') }}</td></tr>@endforelse
</tbody></table></div><div class="admin-pagination">{{ $attractions->links() }}</div></section></main>
<dialog id="deleteAttractionDialog" class="admin-dialog"><form method="POST" id="deleteAttractionForm">@csrf @method('DELETE')<button type="button" class="dialog-x" onclick="this.closest('dialog').close()">&times;</button><span>!</span><h2>{{ __('admin.delete_question') }}</h2><p>{!! __('admin.delete_warning', ['name' => '<strong id="deleteAttractionName"></strong>']) !!}</p><div><button type="button" onclick="this.closest('dialog').close()">{{ __('admin.cancel') }}</button><button type="submit">{{ __('admin.delete_forever') }}</button></div></form></dialog>
<script>const dialog=document.getElementById('deleteAttractionDialog'),form=document.getElementById('deleteAttractionForm');document.querySelectorAll('[data-delete-url]').forEach(b=>b.addEventListener('click',()=>{form.action=b.dataset.deleteUrl;document.getElementById('deleteAttractionName').textContent=b.dataset.name;dialog.showModal()}));</script></body></html>
