<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Manage Attractions - ExploreMY Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/dashboard.css') }}"><link rel="stylesheet" href="{{ asset('css/admin.css') }}"></head><body>
@include('components.admin-navbar')
<main class="container admin-page"><header class="admin-heading"><div><span>ExploreMY administration</span><h1>Attraction management</h1><p>Add, review and maintain the places available throughout the system.</p></div><a href="{{ route('admin.attractions.create') }}">+ Add attraction</a></header>
@if(session('success'))<div class="admin-alert">{{ session('success') }}</div>@endif
<section class="admin-summary"><div><small>Total attractions</small><strong>{{ $attractions->total() }}</strong></div><form method="GET"><input type="search" name="search" value="{{ request('search') }}" placeholder="Search name or location..."><button>Search</button>@if(request('search'))<a href="{{ route('admin.attractions.index') }}">Clear</a>@endif</form></section>
<section class="admin-table-card"><div class="admin-table-wrap"><table><thead><tr><th>Attraction</th><th>State</th><th>Category</th><th>Rating</th><th>Saved</th><th>Actions</th></tr></thead><tbody>
@forelse($attractions as $attraction)<tr><td><div class="admin-place"><span>@if($attraction->image_path)<img src="{{ $attraction->image_path }}" alt="">@else{{ Str::upper(Str::substr($attraction->attraction_name,0,2)) }}@endif</span><div><strong>{{ $attraction->attraction_name }}</strong><small>{{ Str::limit($attraction->location,55) }}</small></div></div></td><td>{{ $attraction->state->state_name }}</td><td>{{ $attraction->category ?: '—' }}</td><td>{{ $attraction->rating ? number_format($attraction->rating,1) : '—' }}</td><td>{{ $attraction->saved_by_users_count }}</td><td><div class="table-actions"><a href="{{ route('admin.attractions.edit',$attraction) }}">Edit</a><button type="button" data-delete-url="{{ route('admin.attractions.destroy',$attraction) }}" data-name="{{ $attraction->attraction_name }}">Delete</button></div></td></tr>
@empty<tr><td colspan="6" class="admin-empty">No attractions found.</td></tr>@endforelse
</tbody></table></div><div class="admin-pagination">{{ $attractions->links() }}</div></section></main>
<dialog id="deleteAttractionDialog" class="admin-dialog"><form method="POST" id="deleteAttractionForm">@csrf @method('DELETE')<button type="button" class="dialog-x" onclick="this.closest('dialog').close()">&times;</button><span>!</span><h2>Delete attraction?</h2><p>This will permanently delete <strong id="deleteAttractionName"></strong> and remove it from every user's saved places.</p><div><button type="button" onclick="this.closest('dialog').close()">Cancel</button><button type="submit">Delete permanently</button></div></form></dialog>
<script>const dialog=document.getElementById('deleteAttractionDialog'),form=document.getElementById('deleteAttractionForm');document.querySelectorAll('[data-delete-url]').forEach(b=>b.addEventListener('click',()=>{form.action=b.dataset.deleteUrl;document.getElementById('deleteAttractionName').textContent=b.dataset.name;dialog.showModal()}));</script></body></html>
